### ISSUE TITLE
Binding error by using the UC 2015 release version from the R-Shell environment

### ISSUE THREAD

**Issue by gisfromscratch** [R-ArcGIS/r-bridge#1]
I am using ArcGIS Pro 1.1 and R 3.1.3 for Windows as suggested. The library loads fine into the x64 Version of the R-Shell. If I call check_product the following error occurs:

```Error in .call_proxy("arc_AoInitialize").
"Could not bind to a valid ArcGIS Installation".```

Is this UC release meant to be used with ArcGIS Pro 1.1 or are there any ArcGIS for Desktop dependencies?

**Comment by scw** [comment]
Thanks for the report -- I'll try to reproduce it locally, and get back to you soon.

**Comment by dpavlushko** [comment]
Please run ArcGIS Pro and sign in into your portals account. Open Licensing dialog (click on PROJECT tab) and check current ArcGIS Pro License list, exist app. Run R-Shell again load arcgisbinding package and call check_proguct.

**Comment by gisfromscratch** [comment]
Here is my current license tab:

![pro_license](https://cloud.githubusercontent.com/assets/921231/9190816/34a23a64-3ffa-11e5-85a3-2c0bd7098d2f.png)

So, the license should be valid. We do not want to setup our own development environment, maybe putting the debug symbols to the Esri Symbol Server or just into the release package would allow us to debug it with WinDbg. If to less logging is done, we have to ```analyze! -v``` it!

**Comment by gisfromscratch** [comment]
We were able to workaround this issue. The initialization of the bridge fails when ArcGIS Pro was installed with the "only for me" option. Using this options the installer add the necessary registration entries under HKCU. The initialization of AO does not handle this case. So you have to create the registries entries under [HKEY_LOCAL_MACHINE\SOFTWARE\ESRI\ArcGISPro].

Can this be easily fixed in a future release?

**Comment by mattniblett** [comment]
I get this same issue as well using ArcGIS 10.3.1 Advanced, and the build that's on GitHub as of 11/3/2015.

**Comment by scw** [comment]
Matt,

ArcGIS 10.3.1 only installs to the overall system (e.g. HKLM), so it's probably the same error but a different issue under the hood. Could you provide details about what version and platform (e.g. R 3.2 32-bit) of R you're using it with and we can try to suss out the issue. Does it work from the R prompt but not ArcGIS, or fails in both cases?

**Comment by mattniblett** [comment]
Hi scw,
I'm using R 3.2.2 "Fire Safety" 64bit version on Windows 7 64bit. It seems like everything is installed to the proper directory too. The arcgisbinding library is installed into the R libraries and all of the files to support it appear. ArcGIS can see R, and I can run the built-in toolbox methods from the default toolbox within ArcCatalog and ArcMap and it reports the correct version of R. However, when I load the library in R using library(arcgisbinding), I get the message: 
"*** Please call arc.check_product() to  define a desktop license." 

When I run the arc.check_product() function, I get the following error 
"Error in .call_proxy("arc_AoInitialize") : 
  Could not bind to a valid ArcGIS installation"

**Comment by dpavlushko** [comment]
Standalone R 64bit require ArcGIS Pro. If you have only ArcGIS 10.3.1 then use R for 32bit.

**Comment by mattniblett** [comment]
I set R to 32bit mode and it in fact works. However, I should have also mentioned that I have 64-bit background geo-processing installed and enabled, which is what I'm trying to use. The graphic on the r-bridge-install page, and in the documentation, is not correct and is misleading if it's the case that ONLY the 32-bit version of R is supported, even with 64bit background geoprocessing.

**Comment by scw** [comment]
Background Geoprocessing will work with 64-bit R -- but only when called from within the ArcGIS application, not from standalone R. So if you create a Geoprocessing script which calls into R, it will correctly use the R 64-bit environment, but that isn't currently possible from within R itself. I'll look at clarifying the diagram and documentation to reflect this.

**Comment by scw** [comment]
@mattniblett I've updated the diagram and the prerequisites section to reflect the requirement to access 64-bit R from within the application.

**Comment by scw** [comment]
Marking this closed as the original issue with the "for me only" installation of ArcGIS Pro now works with the bridge properly, and is independently verified. @mattniblett, feel free to open a separate issue if needed.
