### ISSUE TITLE
arc.write() won't populate a feature dataset.

### ISSUE THREAD

**Issue by MMMcMahon** [R-ArcGIS/r-bridge#11]
Hi all,

I'm not sure if this is an issue, or just me.  :)

In the following part of the details section of the arc.write() documentation, it indicates that features can be written to a geodatabase feature dataset, but I can not get this to work.

> Supports a variety of output formats. Below are pairs of example paths and the resulting data types:
> ...
> C:/place.gdb/fdataset/fc: File Geodatabase Feature Dataset

When I send a value for a path that is 1 level inside a gdb file (i.e. a feature dataset), my data gets written into the geodatabase (which is awesome), but it is not being written _into_ the desired feature dataset, just within the root of the gdb  I'm doing something like:
~~~~
theGDB = "C:/stuff/mygeodatabase.gdb"
theFD = "fdataset"
thisFeature = "FeatureX"
arc.write(path = paste0(theGDB,"/",theFD,"/",thisFeature), data = spatial_data, coords = list(spatial_data@data$LONG, spatial_data@data$LAT))
~~~~
I had thought that it had to do with the coordinate system of the feature dataset matching my features, but if I manually drag my created features from the root of the gdb into the feature dataset manually (in ArcCatalog), they go just fine. 

The fact that my data is indeed being written gives me confidence that I'm on the right track, but since I want to script the creation of almost 3000 features and use feature datasets to categorize them makes the feature datasets pretty important.

Thanks for any tips or insight.

**Comment by dpavlushko** [comment]
Fixed in [1.0.1.229](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta)
