### ISSUE TITLE
ArcGIS Pro crashes when trying to detect R

### ISSUE THREAD

**Issue by katharineegan** [R-ArcGIS/r-bridge#16]
Hello, 

I'm trying to complete the "Using the R-ArcGIS Bridge" web course through Esri for class. I can't get passed the installing R-ArcGIS Bridge particularly the first part which is this in the training: 

"I will navigate to the R-ArcGIS Support options by clicking the Project tab and selecting Options and then view the geoprocessing options." 

Every single time I've tried to do this, ArcGIS Pro crashes immediately, and I get this error report: 
![image](https://user-images.githubusercontent.com/12935901/29973675-c1a34180-8f06-11e7-8816-52f438f21362.png)

I have R v3.4 and ArcGIS Pro 2.0. I also have RStudio installed. Any help would be appreciated.

**Comment by scw** [comment]
@katharineegan I'm sorry to hear about this issue and am happy to help try and fix it. Could you submit the issue and include my email address in the description field? My email is: s walbridge  @ esri.com, all as one word, without the spaces. If you have existing crash files that are generated, you can also just email those to me directly. To find the existing crash dumps, navigate in File Explorer to:

    %LOCALAPPDATA%\Esri\ErrorReports

As a workaround for now to get you up and running with the bridge, could you download [the bridge installer toolbox](https://github.com/R-ArcGIS/r-bridge-install)? This installation method won't require you to visit the options > Geoprocessing pane, and provides some other details on the install. It'll work fine with any recent version of ArcMap or ArcGIS Pro. It also includes a basic diagnostic tool for checking the R environment, "R Installation Details". Could you run that tool and send on what it reports? That may be helpful for us to debug the specific configuration that's causing the crash. It looks like you're on Windows 10, is that correct?

**Comment by scdub** [comment]
@katharineegan I haven't heard back from you on your issue, but if you're still having crashes, please either submit the crash dump, or let us know here and we can follow up.

Cheers, Shaun
