### ISSUE TITLE
Add ability to detect and delete feature classes

### ISSUE THREAD

**Issue by bltern** [R-ArcGIS/r-bridge#18]
It would be very nice, actually it's really necessary, to have the ability to delete feature classes from a File Geodatabase from R via the r-bridge. It's very tedious to have to do this manually. Also to see if it exists already would be useful alone.

**Comment by scw** [comment]
@bltern thanks for your report. I agree this is useful, and often necessary functionality if you're using R exclusively for managing your resulting datasets. We'll take this into consideration.

**Comment by dpavlushko** [comment]
`arc.delete()` and `overwrite` flag added in [1.0.1.229](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta)
