### ISSUE TITLE
arc.open() error in .call_proxy

### ISSUE THREAD

**Issue by jerriecheung** [R-ArcGIS/r-bridge#21]
Hello,

I'm using ArcGIS Desktop 10.5
R 3.4.3 32 bits
arc.open() gives Error in .call_proxy("dataset.open", .Object, path) : cannot open dataset
I have no idea how to fix it. Any help would be appreciated!

Rui

**Comment by scw** [comment]
Hello @jerriecheung,

Could you post the code you're using?

Thanks,
Shaun

**Comment by jerriecheung** [comment]
Hi Shaun,

telecoupling-toolbox/arcgis-toolbox/Scripts/NetworkAnalysis.R
This is the script I'm trying to run. It simply has a shapefile as an input parameter and use arc.open() to read the file.

I also tried the example within R help like:
arc.open(system.file("FOLDER","SAMPLE DATA", package = "arcgisbinding"))
and it throws the same error.

Thanks,
Rui

**Comment by scw** [comment]
Does this work?

```
filename <- system.file("extdata", "ca_ozone_pts.shp",
                          package = "arcgisbinding")
d <- arc.open(filename)
cat('all fields:', names(d@fields), fill = TRUE) # print all fields
```
I can't see the source of NetworkAnalysis.R, but if you can copy the lines around where it is failing, that would be helpful.

Cheers,
Shaun

**Comment by jerriecheung** [comment]
Hi Shaun,

I tried the code you suggested, it gives the error at d <- arc.open(filename).

The script I'm trying to run 

tool_exec <- function(in_params, out_params)
{
	#Load library
	if (!requireNamespace("igraph", quietly = TRUE))
    	install.packages("igraph")
  	if (!requireNamespace("RColorBrewer", quietly = TRUE))
    	install.packages("RColorBrewer")
  	if (!requireNamespace("dplyr", quietly = TRUE))
    	install.packages("dplyr")
	if (!requireNamespace("sp", quietly = TRUE))
    	install.packages("sp")

  	require(igraph)
	require(dplyr)
	require(sp)

        input_nodes_table <- in_params[[1]]
	input_link_table <- in_params[[2]]
	input_telecoupling_system <- in_params[[3]]
	clustering_algorithm <- in_params[[4]]
        ......

        WC <- arc.open(input_telecoupling_system)
	str_lst <- paste0("'", paste(df$ISO_3_CODE, collapse="', '"), "'")
	WC_df <- arc.select(WC, where_clause = paste0('ISO_3_CODE IN (', str_lst, ')'))
        ......
}

It fails at the line WC <- arc.open(input_telecoupling_system) with message 
Error in .call_proxy("dataset.open", .Object, path) : cannot open dataset

**Comment by scw** [comment]
Hi @jerriecheung,

If the package fails to load the sample dataset, I'd recommend reinstalling the bridge. If that doesn't work, try repairing the ArcGIS Desktop installation from the Control Panel.

Cheers,
Shaun

**Comment by scdub** [comment]
@jerriecheung closing this issue as its pretty old at this point -- but if you do have problems working with the bridge, let us know.

**Comment by Nova-Scotia** [comment]
I had a similar problem in 2020 (arc.select could not open the dataset). I'm using R 4.0.2.

Reinstalling just the `arcgisbinding` package worked for me.

`install.packages("arcgisbinding", repos="https://r.esri.com", type="win.binary")`

**Comment by Yaw1517** [comment]
Hello,

I'm using Jupiter notebook in conjuction with ArcGIS Pro 2.5
I am trying to run read in the time-series mosaic that contains the predicted temperature profiles, but always giving me errors
below are the codes
## INITIALIZE CONNECTION WITH ARCGIS PRO arc.check_product()
## Define the location for GDB containing rasters
r <- arc.open('C:/CAnalysis/p20/Default.gdb/temp_time_series')
## Read In Time Series Mosaic Times
forecast_times <- arc.select(r)
forecast_times <- as.Date(forecast_times$StdTime)

**Comment by Yaw1517** [comment]
Pls any help would be aprreciated

**Comment by Aynalem6** [comment]
Can anyone help with this error

error in .call_proxy("dataset.open", .object, path) : cannot open dataset

**Comment by scdub** [comment]
@Aynalem6 Can you provide the call to `arc.open` that you are executing? What kind of data are you working with?

**Comment by Alejandr0-r** [comment]
I am trying to do the Esri Training called "Using the R-ArcGIS Bridge" and when I try to load the spatial data I get this error:

Error in .call_proxy("dataset.open", .Object, path) : cannot open dataset

Has anyone dealt with this before?

Thanks in advance!

**Comment by JosiahParry** [comment]
@Alejandr0-r You are probably misspecifying the path to the file. Is [this the course](https://www.esri.com/training/catalog/5e7a1c9217148e49007970ff/rarcgis-bridge-essentials/) you are working on?

**Comment by Alejandr0-r** [comment]
@JosiahParry It's this one: https://www.esri.com/training/catalog/58b5e417b89b7e000d8bfe45/using-the-r-arcgis-bridge/#!

**Comment by cayates2** [comment]
Probably a bit too late to the party, but for anyone else having issues with this. ArcGIS Pro does not use the same relative path method that RStudio can read. Make sure to use the FULL PATH instead of the ~\\ relative one.
