### ISSUE TITLE
arc.write error with version 1.0.1.231

### ISSUE THREAD

**Issue by andyfarmerboy** [R-ArcGIS/r-bridge#24]
Previously working code returns an error after updating arcgisbinding package to 1.0.1.231
`arc.write("E:\\file.shp", sp_table)`
returns
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘arc.shapeinfo’ for signature ‘"NULL"’
```

**Comment by dpavlushko** [comment]
Please update package to version 1.0.1.232.

**Comment by andyfarmerboy** [comment]
That fixed the issue.  Thanks for patching.
