### ISSUE TITLE
Error: Could not bind to a valid ArcGIS Pro installation

### ISSUE THREAD

**Issue by ftm610** [R-ArcGIS/r-bridge#25]
Biding fails (using both RStudio and RGui) with ArcGIS Pro, but successful with ArcGIS Desktop.  ArcGIS Pro is using Single Use License (while also logged into ArcGIS Online account).  Binding is successful to ArcGIS Pro on similarly configured machine (OS and software versions) with Named User License.  License type issue?

Windows 10 Pro
arcgisbinding version 1.0.1.232

**ArcGIS Pro Binding - FAILED** 
ArcGIS Pro 2.2.0
Single Use License - Advanced

```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Platform: x86_64-w64-mingw32/x64 (64-bit)

> library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.
> arc.check_product()
Error: Could not bind to a valid ArcGIS Pro installation.
```

Installation successfully confirmed from RIntegration.pyt script...
```
Running script RInstallDetails...
R (version 3.5.1), installed in: C:\Program Files\R\R-3.5.1
R packages will be installed into: D:\Documents\R\win-library\3.5
All R package libraries detected: D:\Documents\R\win-library\3.5;C:\Program Files\R\R-3.5.1\library
The ArcGIS R package (version 1.0.1.232) is installed at: D:\Documents\R\win-library\3.5\arcgisbinding
Completed script R Installation Details...
```

**ArcGIS Desktop Binding SUCCESSFUL**

```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Platform: i386-w64-mingw32/i386 (32-bit)

> library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.
> 
> arc.check_product()
product: ArcGIS Desktop ( 10.6.0.8321 )
license: Advanced 
version: 1.0.1.232 
```

**Comment by orhuna** [comment]
Hello @ftm610 

Can you please check to see whether ```bin``` folder for ArcGIS Pro is in ```Path``` environment variable? 

We often have this issue if for some reason the ```bin``` folder is not added to the path automatically after install. Probably your Desktop's ```bin``` folder is under Path but not ArcGIS Pro.

**Comment by JerryChase** [comment]
I experienced the same problem. The following worked for me:
1. In RStudio I chose: Tools/Install Packages 
2. From the Browse button I selected the latest arcgisbinding package archive (arcgisbinding_1.0.1.232.zip) and then clicked Install.

Following this I was able to successfully call library(arcgisbinding). Perhaps this will work for others.

**Comment by ftm610** [comment]
Thanks @orhuna.  Adding ArcGISPro bin folder to Path solved the issue.  
```
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Platform: x86_64-w64-mingw32/x64 (64-bit)

> library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.
> 
> arc.check_product()
product: ArcGIS Pro ( 12.2.0.12813 )
license: Advanced 
version: 1.0.1.232 
```

Odd that I can call this library on a different machine without AGP bin folder in Path.  But whatever, easy fix and now up and running.
