### ISSUE TITLE
arcgisbinding without ArcGIS?

### ISSUE THREAD

**Issue by ratnanil** [R-ArcGIS/r-bridge#28]
Nice work on your part the R-ArcGIS Bridge! 

My question: Is is possible to use some of the package functionalities without having ArcGIS installed? We would like to use the `arcgisbinding ` Package to connect R to an ArcGIS Server, where some users might not necessarily have ArcGIS Installed.

PS: Is the package `arcgisbinding` going to be on CRAN at some point?

**Comment by dpavlushko** [comment]
`arcgisbinding` is just a "bridge". You have to have ArcGIS installed on each client to connect to an ArcGIS Server. 

`arcgisbinding` is a commercial product, it require Visual Studio C++ compiler and uses Windows API, so we cannot put the package on CRAN.

**Comment by ratnanil** [comment]
Hey @dpavlushko, thanks for clarifying. We'll try to find a workaround!
