### ISSUE TITLE
creating an empty geodatabase?

### ISSUE THREAD

**Issue by ChristopherTracey** [R-ArcGIS/r-bridge#29]
I couldn't find anything about this in the manual or examples, but is it possible to create a empty geodatabase using the bridge?

**Comment by orhuna** [comment]
Our suggested use pattern for arc.write is for writing feature classes and rasters. You can use ArcGIS [Pro](https://pro.arcgis.com/en/pro-app/help/data/geodatabases/overview/create-a-file-geodatabase.htm) (or [Desktop](http://desktop.arcgis.com/en/arcmap/10.3/manage-data/administer-file-gdbs/create-file-geodatabase.htm)) functions to perform this task if this is one time task,

If you need to perform this task in a loop, I suggest using Python automation or using reticulate if you would like to keep your work in one script.

**Comment by ChristopherTracey** [comment]
Thanks. It's more the second example of needing it the loop/script.  I'll try reticulate (we've had issues with it hanging up RStudio).
