### ISSUE TITLE
R and RStudio crash when calling arc.check_product()

### ISSUE THREAD

**Issue by jhw429** [R-ArcGIS/r-bridge#3]
Hi,

since today both R and RStudio crash when I call arc.check_product() so I cannot access the R-ArcGIS Bridge from R anymore. Any ideas? I work with RStudio 0.99.893 and R3.2.4, I have ArcMap 10.4 and ArcGIS Pro 1.2 installed on Windows 10, and I can access the R-ArcGIS Bridge from ArcGIS for Desktop without any problem.

Thanks, Jan

**Comment by scw** [comment]
Hi @jhw429,

Would you be able to try the new release of R, 3.2.5, and see if it eliminates the problem? It can [be downloaded](https://cloud.r-project.org/bin/windows/base/) from the R site. We've had some reports of issues related to the 3.2.4 revised release, and want to see if that relates to the issue you're having.

Thanks,
Shaun

**Comment by scw** [comment]
@jhw429 I'm going to close this issue, as we haven't heard back from you yet, and we have many folks who are working with RStudio just fine. If this continues to be a problem for you, feel free to reopen the issue and we can take a look.
