### ISSUE TITLE
Setting up the r-bridge with python toolbox

### ISSUE THREAD

**Issue by ratnanil** [R-ArcGIS/r-bridge#30]
As I understand, running `R` with the r-bridge is similar to creating a [script tool](https://pro.arcgis.com/de/pro-app/arcpy/geoprocessing_and_python/adding-a-script-tool.htm). However, I've come to love the way I can create the GUI for my tools using the [python toolbox ](https://pro.arcgis.com/de/pro-app/arcpy/geoprocessing_and_python/creating-a-new-python-toolbox.htm) pyt files. Is there a way to use the r-bridge with the python toolbox approach? I.e. that I define my parameters with `arcpy.Parameter()` and I run my R-Script in the `execute()`-Function?

**Comment by dpavlushko** [comment]
It you have an existing R script tool it's not a problem, arcpy API allow import toolbox and execute tool.

**Comment by ratnanil** [comment]
Thank you for the quick answer! I've tried this out, but apparently I still need to define my parameters in the toolbox? So I can't *just* specify them in my python toolbox? The error I'm getting is the following:

`TypeError: Script() takes 0 positional arguments but 1 was given
`

**Comment by ratnanil** [comment]
For reference, I tried this out in the following manner:

1. Created a toolbox with the name *New Toolbox.tbx* and the alias *NewToolbox*
2. Created an R File with the name *test.R* with the following lines of code:

```
tool_exec <- function(in_params, out_params){
  print(in_params[[1]])
}
```
3. Created a script tool with the name *Script*, pointing to the File *test.R* in the Tool properties
4. Added a parameter in my Toolbox for testing purposes, deleted this parameter again after making sure the tool works (prints the input parameter to the console)
5. Created a new tool in my python toolbox and imported the toolbox like so:

```
arcpy.ImportToolbox("New Toolbox.tbx")
arcpy.Script_NewToolbox(parameters[0])
```
6. added an `arcpy` Parameter like so:

```
arcpy.Parameter(displayName="Feature Dataset",name="fds",datatype="GPLong")
```

**Comment by dpavlushko** [comment]
You are in the right direction.
I attached [hello.zip toolbox](https://github.com/R-ArcGIS/r-bridge/files/3056386/hello.zip) example.
In general two GP tools communication:
R tool:
```R
tool_exec <- function(in_params, out_params)
{
  out_params[[1]] <- paste("From R tool. Hello", in_params[[1]], "!!!")
  return (out_params)
} 
```
Python tool:
```python
import arcpy, os
tbx_path = os.path.join(os.path.dirname(__file__), "test_scripts.tbx")
arcpy.ImportToolbox(tbx_path, "test")
msg = arcpy.test.callR("Bob")[0]
arcpy.AddMessage(msg)
```
Here is `test2` result:
![image](https://user-images.githubusercontent.com/12039804/55759933-89895980-5a0f-11e9-8544-d63905332af3.png)

So, your need to make a few adjustments to make it work in `.pyt` toolbox/tools.

**Comment by ratnanil** [comment]
Thank you for this example which works very nicely. But I see that you defined your input/output parameters *in the toolbox*. There is no way to define the parameter ONLY in the *python* toolbox? 

Background: I'm trying to minimize interaction with the GUI when creating my toolboxes, which is why I prefer _python_ toolboxes over "normal" toolboxes.

**Comment by dpavlushko** [comment]
OK. Make your toolbox/tools in Python dynamically and one fixed R tool with multi-value of string, do your own protocol and type coercion in and out.

**Comment by ratnanil** [comment]
This looks like a very promising approach. I will try it out and report back.

**Comment by ratnanil** [comment]
> OK. Make your toolbox/tools in Python dynamically and one fixed R tool with multi-value of string, do your own protocol and type coercion in and out.

this works, thanks for the tipp!
