### ISSUE TITLE
ArcGIS crashes when running R 3.6.*

### ISSUE THREAD

**Issue by mpdougherty** [R-ArcGIS/r-bridge#34]
Both ArcGIS Pro and ArcGIS Desktop crash when running R code using the r-bridge with R 3.6.* and arcgisbinding 1.0.1.235. This behavior is reproducible on multiple Win 10.1709 computers. Based on the following test results, it appears the only current workaround is to run R 3.5.* WITH arcgisbinding 1.0.1.232. 

ArcGIS
Works: ArcGIS Pro 2.4.0; R 3.5.1; arcgisbinding 1.0.1.232
Works: ArcGIS Desktop 10.7.1; R 3.5.1; arcgisbinding 1.0.1.232

Crash: ArcGIS Pro 2.4.0; R 3.5.1; arcgisbinding 1.0.1.235
Crash: ArcGIS Pro 2.4.0; R 3.6.1; arcgisbinding 1.0.1.235
Crash: ArcGIS Pro 2.4.0; R 3.6.1; arcgisbinding 1.0.1.232
Crash: ArcGIS Desktop 10.7.1; R 3.6.1; arcgisbinding 1.0.1.235
Crash: ArcGIS Desktop 10.7.1; R 3.6.1; arcgisbinding 1.0.1.232

R Console (RStudio)
Works:  R 3.5.1 x64; arcgisbinding 1.0.1.235
Works:  R 3.6.1 x64; arcgisbinding 1.0.1.235
Works:  R 3.5.1 i386; arcgisbinding 1.0.1.235
Works:  R 3.6.1 i386; arcgisbinding 1.0.1.235

**Comment by orhuna** [comment]
I can repro with a custom tbx on ArcGIS Pro 2.4.2; R 3.6.1; arcgisbinding 1.0.1.235.

@dpavlushko attached is the crash dump.
[ArcGISPro_2.4.2.19948_EA17F0DD-1CC8-46F9-A770-2668F7CBC03D_10_08_2019_16_30_04.dmp.zip](https://github.com/R-ArcGIS/r-bridge/files/3704910/ArcGISPro_2.4.2.19948_EA17F0DD-1CC8-46F9-A770-2668F7CBC03D_10_08_2019_16_30_04.dmp.zip)

**Comment by orhuna** [comment]
@mpdougherty The crash is fixed in the `v237` of `arcgisbinding` package. Can you please re-install the bridge? When installing the bridge please make sure to not have any active R instance running on your machine. Active R sessions include:
- R Gui
- R Studio
- Console calling R
- Instance of ArcGIS Pro that executed (successfully or unsuccessfully) and R Script Tool.

**Comment by mpdougherty** [comment]
@orhuna I was able to upgrade `arcgisbinding` to `237` and can confirm that it is working correctly for both ArcMap and Pro. Thanks so much for getting this fixed so quickly!

**Comment by orhuna** [comment]
@mpdougherty Excellent news! Thank you for letting us know.
