### ISSUE TITLE
Read files from database connection

### ISSUE THREAD

**Issue by plnnr** [R-ArcGIS/r-bridge#35]
Not sure if this is an issue, or simply an inquiry about features. I'm trying to read layers from a database server connection. Is this possible? My connection string looks like this:

```
library(DBI)
library(odbc)
con <- dbConnect(odbc(), 
                 Driver = "SQL Server", 
                 Server = "GIS_DB", 
                 Database = "MY_PUBLIC_DB", 
                 UID = rstudioapi::askForPassword("Database user"),
                 PWD = rstudioapi::askForPassword("Database password"),
                 Trusted_Connection = "True")
```

Is there any way we can use `arc.open()` or another function on `con`? The issue is that I want to read tables and layers from the database, but raw SQL queries like the example below can sometimes block the connection to our server for other enterprise users

```my_layer <- dbFetch(dbSendQuery(con, 'select * from MY_PUBLIC_DB.ARCMAP_ADMIN.MY_LAYER'))```

**Comment by dpavlushko** [comment]
Create new Database Connection file or Ole DB Connection in ArcGISPro/ArcMap.

![image](https://user-images.githubusercontent.com/12039804/85476335-f46b7580-b56c-11ea-9e0f-5e10ecd7e7b6.png)

Append table name to the full path and use  `arc.open(),arc.select()`
Example:
```R
> d <- arc.open("C:\\gpegdb.sde\\GP.fc1")
> d
dataset_type    : FeatureClass
path            : C:\gpegdb.sde\GP.fc1 
fields          : OBJECTID, LINK1, MERGE_SRC, SHAPE
extent          : xmin=705092.7, ymin=2132003, xmax=836676.4, ymax=2237493
geometry type   : Point
WKT             : PROJCS["NTF_Lambert_II_étendu",GEOGCS["GCS_NTF",DATUM["D_NTF...

```
