### ISSUE TITLE
ready for R 4.0?

### ISSUE THREAD

**Issue by ChristopherTracey** [R-ArcGIS/r-bridge#37]
Tried upgrading to R 4.0 tonight and hit this error when trying to load the bridge library:
`Error: package 'arcgisbinding' was built before 4.0.0: please-re-install it`

Tried several times without success. Using Arcgis Pro to install the bridge but manual installs from the zip don't seem to work either.

**Comment by scdub** [comment]
@ChristopherTracey we don't yet support R 4.0, it'll probably be a couple weeks or so before we can marshal resources &mdash; we need to figure out a way to concurrently support both releases at the same time.

Best wishes,
Shaun

**Comment by mvkorpel** [comment]
I was able to install the package on R 4.0 by following the build instructions (without Visual Studio) in README.md. So far I have tested that reading data from a file geodatabase works. Is there any problem related to this approach?

**Comment by orhuna** [comment]
@mvkorpel This approach should be fine. Currently, we have a more direct means of setting up `arcgisbinding` with R 4.0. Simply run the command below in your R console:

install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")

**Comment by Orione1111** [comment]
Hi orhuna, the command failed...
> install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")
Installing package into ‘C:/Users/ORIONE/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
tentando a URL 'http://r-arcgis.github.io/r-bridge/bin/windows/contrib/4.0/..//arcgisbinding_1.0.1.239.zip'
Warning in install.packages :
  cannot open URL 'http://r-arcgis.github.io/r-bridge/bin/windows/contrib/4.0/..//arcgisbinding_1.0.1.239.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  não foi possível abrir a URL 'http://r-arcgis.github.io/r-bridge/bin/windows/contrib/4.0/..//arcgisbinding_1.0.1.239.zip'
Warning in install.packages :
  download of package ‘arcgisbinding’ failed

**Comment by dpavlushko** [comment]
@Orione1111 Looks like you trying to install arcgisbinding on R4 32bit. At this moment we only support x64 architecture. If your Windows system is 64bit then rung Rgui.exe from `C:\Program Files\R\R-4.0.0\bin\x64` and try again.

**Comment by dpavlushko** [comment]
@Orione1111 If you still looking for arcgisbinding 32-bit version for R 4.0, please re-run following command: 
```R
> install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")
```

**Comment by orhuna** [comment]
@Orione1111 the `v242` for `arcgisbinding` has fixes for R.4.0. please let us know if you run into any issues with the latest version.

**Comment by mpdougherty** [comment]
Great news!

**Comment by Nova-Scotia** [comment]
If you're working on a 64 bit computer this worked for me (mentioned in another post, but maybe this will help someone else):
`install.packages("arcgisbinding", repos="https://r.esri.com", type="win.binary")`
