### ISSUE TITLE
Error in .call_proxy("dataset.open", .Object, path)

### ISSUE THREAD

**Issue by gregforcey** [R-ArcGIS/r-bridge#39]
Possibly related to this issue: https://github.com/R-ArcGIS/r-bridge/issues/21 but none of the solutions in that thread worked.

I've previously been able to import feature classes from geodatabase using the r-bridge, but now I'm receiving an error that I never got before on the same code. I upgraded to R 4.02 and thus installed the latest version from here: https://github.com/R-ArcGIS/r-bridge/issues/37. This also occurred in R version 3.6.3 with a previous version as well so it does not seem to be related to  R 4.0. 

I tried running the following on the sample data to troubleshoot but got the same error:
```r
    filename <- system.file("extdata", "ca_ozone_pts.shp", package = "arcgisbinding")
    d <- arc.open(filename)
```
The console output was: 
```
Error in .call_proxy("dataset.open", .Object, path) : 
  Class not registered
```
This is on a fresh install of R 4.0 and version 1.0.1.240 of `arcgisbinding`. Any suggestions? Thank you!

**Comment by dpavlushko** [comment]
Please provide output from:
```R
> arc.check_product()
```

**Comment by gregforcey** [comment]
> arc.check_product()

```
product: ArcGIS Pro (12.5.0.22081)
license: Advanced
version: 1.0.1.240 
```

**Comment by dpavlushko** [comment]
Something wrong with COM components. Reinstall `ArcGISPro` and `arcgisbinding`, double check all locations:
```r
> p<-arc.check_product()
> p$path
[1] "C:\\ArcGIS\\"
> dir.exists(p$path)
[1] TRUE
> f<-system.file("extdata", "ca_ozone_pts.shp", package = "arcgisbinding")
> f
[1] "C:/Users/dipa/Documents/R/win-library/4.0/arcgisbinding/extdata/ca_ozone_pts.shp"
> file.exists(f)
[1] TRUE
```

**Comment by gregforcey** [comment]
It seems to be working again after a full uninstall and reinstall of ArcGIS pro. Thanks for the assist.
