### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by gisler** [R-ArcGIS/r-bridge#4]
Hi,

I've got trouble with encoding using arc.write() and the 64bit binding dll of ArcGIS Pro. Here's a minimum example involving shapefiles and attribute data only, but it's the same with FileGDBs:
`library(arcgisbinding)`
`arc.check_product()`
`options(stringsAsFactors = FALSE)`
`setwd("D:/GIS/Test")`
`df.chr <- data.frame("Test" = c("ä", "a", "ß", "s"))`
`Encoding(df.chr$Test)`
`arc.write(paste0(getwd(), "/latin1.shp"), df.chr)`
`df.chr$Test <- enc2utf8(df.chr$Test)`
`Encoding(df.chr$Test)`
`arc.write(paste0(getwd(), "/utf8.shp"), df.chr)`

This is what I get in both cases:
![encoding](https://cloud.githubusercontent.com/assets/19665733/15672625/1cb05736-2732-11e6-8a28-c1882de3ce62.PNG)

I'm using:

- R version 3.2.3 64bit
- arcgisbinding v1.0.0.118
- product: ArcGIS Pro 
- license: Advanced 
- build number: 11.2.0.5023 
- binding dll: rarcproxy_pro

With the 32bit binding dll of ArcGIS Desktop it seems to work though.

Please let me know if you need any additional information.

**Comment by scw** [comment]
Hi @gisler,

Thanks for the report, I can confirm the issue with encoding the characters within the 64-bit environment, and we'll look into the issue.

One note: for the case of shapefiles, by default the data is always exported as UTF-8, so the two resulting files `latin1.dbf` and `utf8.dbf` are identical in the working 32-bit case.

**Comment by dpavlushko** [comment]
Please use Release v1.0.0.119
