### ISSUE TITLE
version: 1.0.1.241 problem

### ISSUE THREAD

**Issue by emrehanks** [R-ArcGIS/r-bridge#42]
Dear Devs,

I tried to install new version of arcgisbinding (v241) unfortunately not working. But v239 work fine. I just wanted to inform you about this problem.
Best regards
**Console Error:** 
_Failed to initialize R interpreter
Failed to execute_

**Comment by orhuna** [comment]
@emrehanks thanks for the bringing this to our attention. What is the version of R you are using? Is the R installed on your machine standalone or a part of a Conda environment you have created with `r-arcgis-essentials` or `r-arcgisbinding`?

**Comment by emrehanks** [comment]
Hi Orhuna, Thanks to respond to my problem. I installed a standalone R 3.6.3 (cran.r-project.org - selected both 32 and 64bit). I encounter this problem the first time. I was able to fix the problem by installing the old version (v239).

**Comment by orhuna** [comment]
@emrehanks this issue should be fixed on v242. Please let me know if the issue persists.
