### ISSUE TITLE
arcgisbindings 1.0.1.241 compatibility with R 4.0.2 and ArcGIS 10.7.1

### ISSUE THREAD

**Issue by ghost** [R-ArcGIS/r-bridge#43]
I haven't yet made the transition to ArcPro and recently upgraded R from 3.5 to 4.0.2.  The arcgisbindings package was working for me using Desktop 10.7.1 and R 3.5 but stopped working when I upgraded R to v4.  I ran the update bindings python script and it appeared to work (shows proper R 4.0.2 folder) but ArcMap keeps throwing "*** Please install ArcGIS R integration package" when I try to run tools that previously worked.  I redownloaded the "master.zip" file and reran the update in ArcCatalog but still got the same thing.  I also installed the arcgisbinding package in the R console and results from arc.check_product() that reflect 10.7.1 and 1.0.1.241.  I can probably get by for a while just using the package in R but I will definitely need to run toolbox tools at some point and prefer not to switch over to ArcPro just yet.  How can I get arcgisbindings to work in ArcGIS when the update script says "The installed ArcGIS R package (version 1.0.1.241) is the current version on GitHub"?

**Comment by orhuna** [comment]
Compatibility issue solved with v242+.
