### ISSUE TITLE
Calling arc.check_portal() causes R Studio session to crash/abort.

### ISSUE THREAD

**Issue by durphyco** [R-ArcGIS/r-bridge#46]
I am having issues calling arc.check_portal() within R Studio. I am new to the arcgis bridge and am trying to test the functionality of the portal data access. I am running R version 4.0.2 and arcgisbinding package version 1.0.1.241. ArcGIS Pro is version 2.6.0.

The crash is occuring directly after loading the arcgisbinding package with library() and calling arc.check_product() as I have done with local uses of the bridge. 

 Please advise; thanks!

**Comment by orhuna** [comment]
@durphyco Below is the snippet I ran to reproduce your error, on ArcGIS 2.6.0 with `arcgisbinding` version 241:

```
library(arcgisbinding)
arc.check_product()
arc.check_portal()
```

Below is the result:
![image](https://user-images.githubusercontent.com/5066435/96050681-e5b41180-0e2e-11eb-8125-1342d5d21566.png)

Can you please share the output of `arc.check_product()`?

**Comment by durphyco** [comment]
Yes, no problem. Your snippet is the exact code I am running. Also, FYI, I tried updating ArcGIS Pro to the latest version (Now I am on version 2.6.2) and got the same crash as I did on 2.6.0, so that doesn't appear to be the issue. Here is the output from arc.check_product():

product: ArcGIS Pro (12.6.2.24783)
license: Advanced
version: 1.0.1.241

**Comment by durphyco** [comment]
I am also getting an R crash when attempting to directly connect to the arcgis.com portal using 

arc.portal_connect("https://www.arcgis.com", username, password)

 I am signed into the arcgis online portal in ArcGIS Pro according to the Portals list under Options.

**Comment by orhuna** [comment]
@durphyco thanks for information above. Can you please try the code snippet I shared with R.exe directly, instead of using R-Studio.

Yours will probably be under `C:\Program Files\R\R-4.0.2\bin` unless you install R somewhere else. Once you launch the R console (R.exe), can you please let me know if you get the same behavior as R-Studio? We ran into some glitches with R-Studio in the past so I want to make sure this is not the case for the problem you are experiencing.

**Comment by durphyco** [comment]
@orhuna OK, I tried that and it just closed the console window. No error message or anything. It just closed upon running  arc.check_portal()

**Comment by dpavlushko** [comment]
@durphyco if you login in ArcGIS Pro to your online account you may skip `arc.check_portal()`, just `arc.check_product()` and call `arc.open()`

**Comment by durphyco** [comment]
@dpavlushko Thanks for the suggestion. This works as a bypass for testing functionality with the arcgis online portal and I am able to open data just fine. However, I will eventually be using the bridge to access my organization's private portal, in which case from my understanding I will likely eventually need the functionality of arc.check_portal() and arc.portal_connect() at some point. 

Any suggestions regarding those specifically causing R to crash?

The end goal of all of this is to share a geoprocessing tool with my organization that includes an R script tool at one step in the ModelBuilder workflow. I have a few additional questions involving this that I will start a new thread to ask.

**Comment by dpavlushko** [comment]
API `arc.check_portal() and arc.portal_connect()` for convenience and custom settings. Before we find out and fix the crash, I suggest: in Pro Portal settings add and connect to all public and private organizations. Use `arc.open()` with proper URI from any connected portal without `arc.check_portal()`.

**Comment by durphyco** [comment]
Will do, thanks. That workaround should work for now. Would appreciate an update when you have found what is causing the crash!

**Comment by orhuna** [comment]
@durphyco we found the cause of the problem and have a new version of the bridge. After QA testing it will out shortly.

**Comment by durphyco** [comment]
@orhuna Excellent, thanks for the update! Let me know when it is released. Thank you for your help!

**Comment by orhuna** [comment]
@durphyco we released version 242 and the portal issue fixed.

**Comment by durphyco** [comment]
@orhuna Thanks for the update and the help!
