### ISSUE TITLE
Failed to initialize R interpreter with arcgisbinding 1.0.1.241 and Pro 2.6.x script tools

### ISSUE THREAD

**Issue by dingusn** [R-ArcGIS/r-bridge#47]
Hi all,

I work for Esri Support Services and I am currently working with a user encountering some issues with the R-ArcGIS bridge post-upgrade. The user upgraded from Pro 2.5.x to 2.6 and also updated the arcgisbinding to the current release, 1.0.1.241. R version is 3.6.3.

Generally Support does not handle R cases, but I wanted to help out the user as much as possible and have reproduced the issue. On Pro 2.6.2 with arcgisbinding 1.0.1.241 and R 3.6.3, attempting to run any R scripts as script tools returns the error message of 'Failed to initialize R interpreter.' Downgrading the library to 1.0.1.239 returns a different error message of 'could not find function 'tool_exec.''

The user reports that their colleagues on Pro 2.4.2 with R versions 3.6.2 and 3.5.0 with arcgisbinding 1.0.1.232 are still able to run R scripts successfully. 

Is there anything we are missing with these errors or some configuration we have incorrect?

**Comment by dpavlushko** [comment]
@dingusn Please confirm all R support settings in Option / Geoprocessing are set.

![image](https://user-images.githubusercontent.com/12039804/96177442-c080db00-0ee2-11eb-8799-3872d8099585.png)

**Comment by dingusn** [comment]
@dpavlushko All settings are set in the Geoprocessing options.
![image](https://user-images.githubusercontent.com/72929779/96179079-55450200-0efe-11eb-9f67-cf91ad0f75d8.png)

Also confirmed in RStudio that arcgisbinding library is installed.
![image](https://user-images.githubusercontent.com/72929779/96179099-5bd37980-0efe-11eb-82ec-eae8400cea04.png)

**Comment by dingusn** [comment]
@orhuna Find the R script attached and screenshot of the error message below. The script only contains a print statement to get the simplest code possible.
[rtest.zip](https://github.com/R-ArcGIS/r-bridge/files/5401104/rtest.zip)
![image](https://user-images.githubusercontent.com/72929779/96435620-bfe29000-11d3-11eb-9bc4-70a20f979aaa.png)

**Comment by gstszhouxj** [comment]
how did you solved last?thanks

**Comment by gstszhouxj** [comment]
how did you solved last?thanks

**Comment by MurphD1rt** [comment]
I am currently facing this issue with ArcGIS Pro 3.3.1, R version 4.4.1, and the arcgisbinding 1.0.1.244
![RandBrigdge_ver](https://github.com/user-attachments/assets/7cda2f61-88dd-487d-bf5a-c806d1d13608)

Were you able to resolve?

**Comment by JosiahParry** [comment]
Please update the arcgisbinding package.
