### ISSUE TITLE
Quick question regarding sharing a geoprocessing tool that includes arc-r bridge elements

### ISSUE THREAD

**Issue by durphyco** [R-ArcGIS/r-bridge#48]
Hi,

I am new to using the Arc-R bridge and have come upon it in my work to build a geoprocessing tool to be shared via a private Portal to my organization. One step in the tool uses an R script which I have successfully turned into an ArcGIS script tool using the bridge functionality, and then incorporated into my ModelBuilder workflow for the geoprocessing tool. The tool runs just fine locally.

Before I share it with the rest of my organization, I want to double check that the R script tool will work in a tool shared via Portal. I might be overthinking this or just flat out wrong about how the bridge works, but my worry is that if another member of my organization were to run the tool within our Portal that the R script would have no R installation to reference, as it seems to do locally on my personal machine. Is this something that will present problems? And, if so, what potential workarounds might I have?

**Comment by scdub** [comment]
@durphyco The step that you would need to do is to set up R within the Server instance that you want to run the Geoprocessing Service that calls R. There are [instructions in the Server documentation](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/deploying-r-for-arcgis-server.htm) to explain this workflow that may help you set this up. But, once you've set up a workflow where a service can run R, then these will be no need for other members to also install R -- they just call the service and use it, it will return the results of the analysis while the R based computation happens on the Server itself.

**Comment by orhuna** [comment]
@durphyco are the steps of setting up in the server and sharing the R-Script tool as a web geoprocessing tool from the Share tab solve this issue?

**Comment by scdub** [comment]
@durphyco I believe the above information should address your issue, if you're still running into problems setting up R based geoprocessing services, let us know.
