### ISSUE TITLE
arc.write() with subset of data frame - length of shape != data.frame length error

### ISSUE THREAD

**Issue by AlexArcPy** [R-ArcGIS/r-bridge#5]
First of all, `arcgisbinding` is an amazing product which enabled me accessing my Esri based datasets directly from R in read/write mode without `rgdal` hustle. Brilliant.

I wonder what is a proper syntax for filtering data frame and then exporting to a new feature class? Running this will work as expected, because I do `arc.write()` on the whole `df`:

```
library(arcgisbinding)
arc.check_product()

data = arc.open(path = 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.4\\TemplateData\\TemplateData.gdb\\USA\\states')
df = arc.select(data,where_clause = "SUB_REGION = 'Pacific' ")

arc.write(path='C:\\GIS\\Temp\\statesPac.shp',data=df)
```

However, trying to filter rows in `df` and writing to the output on-the-fly like this:
```
library(arcgisbinding)
arc.check_product()

data = arc.open(path = 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.4\\TemplateData\\TemplateData.gdb\\USA\\states')
df = arc.select(data)

arc.write(path='C:\\GIS\\Temp\\statesPacX.shp',data=df[df$SUB_REGION == "Pacific",])
```

results in an error message:
```
Warning messages:
1: In: arc.select() - ignoring field: Shape_Length,Shape_Area, 
2: In .call_proxy("arc_export2dataset", path, data, coords, shape_info) :
  length of shape != data.frame length
```

I do get a shapefile created, however, it contains correct states attributes yet the geometry of the features matches other states that were first in the original `df` index. Obviously, I need to filter the geometry of the features while filtering the `df`, but I cannot get how to do that.

Interestingly enough, using the `SpatialDataFrame` does allow me to get my `sdf` filtered on-the-fly:
```
library(arcgisbinding)
arc.check_product()

data = arc.open(path = 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.4\\TemplateData\\TemplateData.gdb\\USA\\states')
df = arc.select(data) #where_clause = "SUB_REGION = 'Pacific' "

sdf = arc.data2sp(df)
sdf = subset(sdf, select = -OBJECTID)

arc.write(path='C:\\GIS\\Temp\\statesPac.shp',data=sdf[sdf$SUB_REGION == "Pacific",])
```

Am I supposed to use the `sdf` or there is a legal way to achieve sub-setting with `df`?

**Comment by dpavlushko** [comment]
Geometry attached to a data.frame as attribute. Thus, any manipulation with rows will make list of geometry elements out of sync. General pattern is to extensively use SQL in arc.select() or convert data.frame to SP then filer rows. If you geometry type is point do it like this:

```R
> d<-arc.open("c:\\data\\points.shp")
> df<-arc.select(d)
> g<-arc.shape(df)
> dfxy<-data.frame(df, g$x, g$y)
#filter rows
> arc.write("c:\\temp\\new_points.shp", dfxy, coords=list(dfxy$g.x, dfxy$g.y), shape_info=arc.shapeinfo(g))
```
