### ISSUE TITLE
R Bridge use with Citrix Receiver hosted ArcGIS Desktop?

### ISSUE THREAD

**Issue by mschmidty** [R-ArcGIS/r-bridge#50]
Is this possible?  Most of my agency accesses Arc remotely, through Citrix.  Very few have local installs of either ArcGIS or ArcPro.  Is there anyway to use r-bridge with this configuration?  Most folks also have ArcGIS online accounts as well.  But it is my understanding that you need to run `arc.check_product()` prior to doing anything else such ase `arc.portal_connect()`.

**Comment by orhuna** [comment]
@mschmidty you are correct, for any functionality of the `arcgisbinding` package to work `arc.check_product()` needs to find a valid Pro license. That requires arcgisbinding package and ArcGIS Pro to be on the same machine. The easiest fix is installing R on the Citrix machine.

**Comment by mschmidty** [comment]
That's what I thought.  Thanks for the response.  Love the package.
