### ISSUE TITLE
repeated fatal error in Rstudio after working with arcgisbinding

### ISSUE THREAD

**Issue by ggold602** [R-ArcGIS/r-bridge#51]
Hello, 
I am running into repeated crashes of Rstudio after downloading and working with arcgisbinding. This happens sometimes before I load arcgisbinding in the project I am working with. ArcGIS Pro, R, and Rstudio are all up to date.  Occurs every time I try to use arc.write. I am a beginner and having difficulty troubleshooting. Attaching diagnostics report.
[diagnostics-report.txt](https://github.com/R-ArcGIS/r-bridge/files/5515124/diagnostics-report.txt)

**Comment by dpavlushko** [comment]
Please show result of `arc.check_product()`.
Also run this simple script as basic test for arc.write() on the fresh R session:
```r
## Example #1. write a shapefile
fc <- arc.open(system.file("extdata", "ca_ozone_pts.shp", package="arcgisbinding"))
d <- arc.select(fc, 'ozone')
d[1,] <- 0.6
arc.write(tempfile("ca_new", fileext=".shp"), d)
```

**Comment by ggold602** [comment]
arc.check_product() connects to ArcGIS Pro 12.6.2. I uninstalled anaconda and have since been able to successfully run arc.write() as well as the example posted.
