### ISSUE TITLE
Can't install package in R v 4.0.2 on Mac

### ISSUE THREAD

**Issue by ryanpdougherty88** [R-ArcGIS/r-bridge#53]
I've been through all the github chats I could find on this subject but still haven't found anything that works. Any help would be appreciated. 

> install.packages("arcgisbinding", repos="https://r.esri.com", type="mac.binary")
Warning in install.packages :
  unable to access index for repository https://r.esri.com/bin/macosx/contrib/4.0:
  cannot open URL 'https://r.esri.com/bin/macosx/contrib/4.0/PACKAGES'
Warning in install.packages :
  package ‘arcgisbinding’ is not available (as a binary package for R version 4.0.2)

> install.packages("arcgisbinding", repos="https://r.esri.com", type="both")
Warning in install.packages :
  unable to access index for repository https://r.esri.com/src/contrib:
  cannot open URL 'https://r.esri.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘arcgisbinding’ is not available (for R version 4.0.2)
Warning in install.packages :
  unable to access index for repository https://r.esri.com/bin/macosx/contrib/4.0:
  cannot open URL 'https://r.esri.com/bin/macosx/contrib/4.0/PACKAGES'

Tried this one too: 
install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="both")
I've switched "type =" to type = "source", type = "both", type = "mac.binary" etc., nothing works.

**Comment by scdub** [comment]
@ryanpdougherty88 thanks for the report. Unfortunately, there isn't any version of the `arcgisbinding` package available for Mac, the package requires that there is [an underlying ArcGIS installation](https://github.com/R-ArcGIS/r-bridge-install/#prerequisites) it can reference, and there isn't at this time a way to use this Windows package on a Mac directly. It will work via Bootcamp or virtualization (e.g. Parallels Desktop).

**Comment by orhuna** [comment]
Closing issue since Mac is currently not supported.
