### ISSUE TITLE
Image service vs map service

### ISSUE THREAD

**Issue by Nova-Scotia** [R-ArcGIS/r-bridge#56]
Hi there,

I think this is a quick "yes" or (likely) "no" question. 

In a previous question I asked about connecting to image services with the R-ArcGIS bridge ([https://github.com/R-ArcGIS/r-bridge/issues/54](https://github.com/R-ArcGIS/r-bridge/issues/54)), which is possible - horay! However, my organization shares most of its base layers as Map Services currently. I'd love to be able to pull them into R using the bridge, but based on [this article](https://www.esri.com/arcgis-blog/products/arcgis-enterprise/imagery/imagery-in-web-applications-should-i-use-a-cached-map-service-or-an-image-service/), it seems unlikely that I'd be able to query and extract imagery from one of those map services into R with the bridge. Is that correct? 

If anyone has experience getting around this, I'm all ears!

**Comment by Nova-Scotia** [comment]
Thanks so much for your thoughtful response and tips! I've been in touch with my organization about the map services - they don't really hold feature data, mostly basemaps, so not sure this would work, but would definitely come in handy for other map services.

**Comment by orhuna** [comment]
@Nova-Scotia for rasters map services are frequently used for efficient visualization. Thus, you may not be able to pull data with `arc.open`. Even if you can, in case map server contains full data definition, you cannot use `arc.raster` functionalities for on-the-fly manipulations such as subsettting and changing projections. Thus, there will be challenges. Note that these challenges are not specific to `arcgisbinding` and are due to the data stored in these services.

Closing this issue as there is a conclusion and no further actions. Please feel free to reopen if you run into issues down the line.

**Comment by Nova-Scotia** [comment]
@JosiahParry might be of interest considering our discussion yesterday...

**Comment by JosiahParry** [comment]
@Nova-Scotia i've started a new package [`{arcgistiles}`](https://github.com/r-arcgis/arcgistiles) which _may_ be in the right direction? it was heavily aided by my buddy Claude—and will need to some heavy handed cleaning and rewriting in the next month or so. But I _think_ this may help? 

Secondly, I think the `arcgisutils::arc_raster()` function will be able to lean on the tiling approach there to help with your resolution issue. The core issue is that an Image Service can only return so many pixels and it will sample if the requested bbox is greater than what it can support (this is a pain for ArcGIS Pro tool development, too, btw).

**Comment by Nova-Scotia** [comment]
This all looks very promising! I'd love to test it out with my own organization's map/image services - should I step back and let you polish a bit first?

Erica




[cid:f312b3ca-7081-46b8-8af7-688d3a7974c1]

Erica Newton (she/her)

Analytical Biologist

***@***.******@***.***>

Wildlife Research and Monitoring Section, MNR



Please Note: As part of providing accessible customer service<https://www.ontario.ca/page/accessible-customer-service-policy>, please let me know if you have any accommodation needs or require communication supports or alternate formats.



________________________________
