### ISSUE TITLE
arc.write not adding features and releasing lock for large datasets

### ISSUE THREAD

**Issue by bltern** [R-ArcGIS/r-bridge#59]
**Describe the bug**
After sucessfully writing a featureclass with 43k records, I can't overwrite again with changes as it gives me the error "Error in .call_proxy("arc_write", path, pairlist(data = data, coords = coords,  : 
  Cannot acquire a lock."

It doesn't error to delete the object if I call arc.delete. 

Upon inspection in ArcCatalog it shows an empty featureclass. So it seems to be trying to create this, but not finishing the write.  I am writing to a server on premises and wondering if it's timing out somehow or otherwise not given enough time to complete the write before closing. I don't think I see this with smaller datasets.

**To Reproduce**
1. Create a large featureclass (>40k records with 35 variable) on a local server using arc.write in R 4.0.4 and Arcgisbinding 1.0.1.244
2. Try to overwrite said featureclass.

**Screenshots**

**arcgisbinding info (please complete the following information):**
 - `arc.check_portal` output
 - R Notebook/ R-Studio/ R IDE:4.04, RStudio 1.4.1717
 - OS: Win10 Pro for Workstations 21H1

**Additional context**

**Comment by orhuna** [comment]
@bltern do you use `overwrite = TRUE` in the `arc.write` call?

**Comment by bltern** [comment]
Yes I do. If I don't it says it exists. The only way I can delete it is in ArcCatalog after it's been partially created. And I can't overwrite either.

**Comment by orhuna** [comment]
@bltern thanks for the information above. As per the steps to reproduce,

```1. Create a large featureclass [...] on a local server using arc.write```

Is this a portal instance or a local geodatabase on machine. We do not have a supported remote writing capability with `arc.write`. Can you please confirm?

**Comment by bltern** [comment]
I am writing to a local NAS server via 1GB wired ethernet connection. I
have  confirmed, just now, that if I move the File GDB to my local machine
it successfully writes the featureclasses that it is failing to achieve
lock on so it seems likely to be related to the latency dealing with the
NAS since it seems capable of writing smaller featureclasses.



*From:* Orhun Aydin ***@***.***>
*Sent:* Monday, August 2, 2021 3:56 PM
*To:* R-ArcGIS/r-bridge ***@***.***>
*Cc:* bltern ***@***.***>; Mention <
***@***.***>
*Subject:* Re: [R-ArcGIS/r-bridge] arc.write not adding features and
releasing lock for large datasets (#59)



@bltern <https://github.com/bltern> thanks for the information above. As
per the steps to reproduce,

1. Create a large featureclass [...] on a local server using arc.write

Is this a portal instance or a local geodatabase on machine. We do not have
a supported remote writing capability with arc.write. Can you please
confirm?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/R-ArcGIS/r-bridge/issues/59#issuecomment-891291229>, or
unsubscribe
