### ISSUE TITLE
Can't load local shapefile

### ISSUE THREAD

**Issue by wraymond** [R-ArcGIS/r-bridge#64]
I recently installed arcgisbinding and was able to walk though the built in dataset (https://r.esri.com/assets/arcgisbinding-vignette.html) but cannot seem to load my own local shapefile.

arc.check_product()
product: ArcGIS Pro (12.7.3.26828)
license: Advanced
version: 1.0.1.244 

R version 4.1.1 64bit
Works fine
`ozone.path <- system.file("extdata", "ca_ozone_pts.shp", package="arcgisbinding")
ozone.arc.dataset <- arc.open(ozone.path)
`

Does not work and returns "Error in .call_proxy("dataset.open", .Object, path) : cannot open dataset"
`mydata <- arc.open("../Data/GIS data/mydata.shp")`

**Comment by scdub** [comment]
@wraymond Did you get this to work? My guess is that the relative path isn't being interpreted correctly.

**Comment by scdub** [comment]
@wraymond Let us know if you're still running into any issues with pathing and shapefiles.
