### ISSUE TITLE
arc.data2sf() returns an sf object that is not valid

### ISSUE THREAD

**Issue by Nibsalot** [R-ArcGIS/r-bridge#65]
**Describe the bug**
Imported multipolygon from a gdb and converted to sf using arc.data2sf() should create a geometry with list of n not list of 1. This needs to be rectified using st_make_valid(). arc.data2sf() should not require st_make_valid() to be applied to a feature.

![image](https://user-images.githubusercontent.com/6210813/168591016-7eb8f145-b95a-4cea-909a-d3bb1342320e.png)

![image](https://user-images.githubusercontent.com/6210813/168591220-bacff228-5664-41af-9b0c-db44eb91c033.png)

**I came across the issue when trying to join projected datasets** 
if features are projected the join only works to one part of the multipolygon

library(sf)
library(arcgisbinding)
library(ggplot2)
arc.check_product()

#importing projected features
multipoly <- arc.select(arc.open("TestData.gdb/MultiPoly_projected_vicgrid"), '*')
points <- arc.select(arc.open("TestData.gdb/Points_projected_vicgrid"), '*')

multipoly_sf <- arc.data2sf(multipoly)
points_sf <- arc.data2sf(points)

###data looks fine
ggplot() + 
  geom_sf(data = multipoly_sf,fill = NA, colour = 'blue',size = 2)+
  geom_sf(data = points_sf,fill = NA, colour = 'black')
![image](https://user-images.githubusercontent.com/6210813/168593248-02ef593d-0630-4588-bccf-91d824208447.png)

#but if i join points to multipolygon join only works on one part of the multipolygon
joined_data <-  st_join(points_sf,multipoly_sf,join=st_within)

ggplot() + 
  geom_sf(data = multipoly_sf,fill = NA, colour = 'blue',size = 2)+
  geom_sf(data = joined_data, aes(colour = Name))
![image](https://user-images.githubusercontent.com/6210813/168593206-16bbfb88-df06-4507-a7e3-84c8978382b3.png)

#set to non projected GDA94
multipoly_sf_gda94  <- st_transform(multipoly_sf , crs = 4283) 
points_sf__gda94 <- st_transform(points_sf, crs = 4283)

#join now works as expected ie. all points with polygon get polygon attribute

joined_data_2 <-  st_join(points_sf__gda94,multipoly_sf_gda94,join=st_within)

ggplot() + 
  geom_sf(data = multipoly_sf_gda94,fill = NA, colour = 'blue',size = 2)+
  geom_sf(data = joined_data_2, aes(colour = Name))
![image](https://user-images.githubusercontent.com/6210813/168593309-b5542e4b-c243-41c9-b324-2bd7072d1a42.png)

#or instead of changing to non projected can make the original projected sf valid. making it a list of n (3 in this case) not list of 1

multipoly_sf_valid <- st_make_valid(multipoly_sf)

#join now works as expected
joined_data_3 <-  st_join(points_sf,multipoly_sf_valid,join=st_within)

ggplot() + 
  geom_sf(data = multipoly_sf,fill = NA, colour = 'blue',size = 2)+
  geom_sf(data = joined_data_3, aes(colour = Name))
![image](https://user-images.githubusercontent.com/6210813/168593322-3b3b3060-e400-442e-9a02-36873e6563e4.png)

**gdb with test data**
[TestData.gdb.zip](https://github.com/R-ArcGIS/r-bridge/files/8699968/TestData.gdb.zip)

**Comment by orhuna** [comment]
@Nibsalot thanks for the notes above. After recreating your repro case and discussing with the team, we concluded that this behavior is as designed. As per the two approaches above, `make-valid` would be the one to go with, especially if the projection is to be preserved.

Note that the tool still yields an `sf` object. There are some cases, like the one above where the geometry might cause the populated dataframe to be invalid, however the main task of the `arc.data2sf` is to populate the `sf` data object with the incoming data.

We will add a usage note in our documentation about using make_valid externally if the resulting dataframe does not support geometry-based operations of sf.
