### ISSUE TITLE
Arc crashes when exporting large datasets to R

### ISSUE THREAD

**Issue by magerton** [R-ArcGIS/r-bridge#7]
I created a custom script tool using the following R script to export data from Arc to R using the 64-bit background processing. Unfortunately, Arc crashes when I use large files (>1.5 or 2 Gb). To remedy this problem, I've had to export the files in chunks. Would be great if I could export things all at once. 

# R-script
```R
tool_exec <- function(in_params, out_params)
{
    library(data.table)

    print(getwd())
    print(in_params)
    
    fcpath     <- in_params[[1]]      
    outvarname <- in_params[[2]]
    outfile    <- in_params[[3]]

    # fields
    fc <- arc.open(fcpath)
    if (is.null(in_params[[4]])) flds <- names(fc@fields)
    else                         flds <- unlist( in_params[[4]] )

    # output datatype
    outtype <- ifelse( is.null(in_params[[5]]), "dt", in_params[[5]])

    # print stuff
    print(paste("saving", outvarname, "as", outtype, "to", outfile))

    # add where_clause = ""

    # import
    if ( is.null(in_params[[6]]) ) {
        if (outtype != "sp") {
            assign(outvarname, data.table(arc.select(fc, fields=flds)))     
        } else if (outtype == "sp") {
            assign(outvarname, arc.data2sp(arc.select(fc, fields=flds)))
        }
    } else {
        where <- in_params[[6]]
        if (outtype != "sp") {
            assign(outvarname, data.table(arc.select(fc, fields=flds, where_clause=where)))     
        } else if (outtype == "sp") {
            assign(outvarname, arc.data2sp(arc.select(fc, fields=flds, where_clause=where)))
        }           
    }
 
    # save
    save(list=outvarname, file=outfile)
}
```

# Python
The toolbox is called rLinkTbx.tbx. Happy to provide via email if helpful.
```python
import arcpy
import time

arcpy.ImportToolbox(dirProj + "/rLinkTbx.tbx", "mytbx")
strdate = time.strftime("%Y-%m-%d", time.localtime())

arcpy.mytbx.saveToR(
    fcpath = gdb + "/" + fc, 
    objectname = fc, 
    outfile = dirOut + fc + "-" + strdate + ".Rdata", 
    fields = "#")
```
![tool-parameters](https://cloud.githubusercontent.com/assets/7339073/20466803/b3deb3f6-af3f-11e6-8485-e7e1c9d2e623.PNG)

![tool-help.pdf](https://github.com/R-ArcGIS/r-bridge/files/602393/tool-help.pdf)

**Comment by dpavlushko** [comment]
Can you identify line when it actually crashes?
Is it `arc.select(), data.table(), arc.data2sp() or save()`?
Start from commenting everything below `arc.select()` run the tool. If it runs okay then add line by line until it crashes again.

**Comment by magerton** [comment]
Thank you, Dmitry. I will do a bit more investigating and get back to you.

**Comment by scw** [comment]
Hello @magerton, have you been able to do any further investigation on this? Thanks!

**Comment by magerton** [comment]
Hi @scw and @dpavlushko , apologies for the delay. I have been running the tool successfully, though not on datasets of a similar size. I will try to do a bit of testing in the next week.

**Comment by scw** [comment]
Great, thanks @magerton. I'd love to have a handle on this issue, and if it persists, fix it and create a regression test.
