### ISSUE TITLE
Survey123 Feature Layers in R

### ISSUE THREAD

**Issue by lauren-obrien** [R-ArcGIS/r-bridge#70]
Hi,

Not sure if this is a bug or intended behavior.

I'm working with a Survey123 dataset in AGOL that has fields where inputs are controlled by drop-down input selectors. The options for these dropdowns were defined with code names that are not human readable, and code labels that are.

When I view the associated spatial point feature class in ArcGIS Pro, I can see that the human-readable labels have been linked to (most of) these fields using a Domain, so the contents are aliased. Unfortunately, this is not preserved when I `arc.select()` the Feature Class into R - I only get the raw code names. 

Is there something I can do with `where_clause` to fix this, or am I stuck?

**Comment by dpavlushko** [comment]
Can you share your tool and script so I can see the issue in detail?

**Comment by lauren-obrien** [comment]
Sure - hopefully this is enough,

1. Points dataset from the survey, viewed in Pro - note the highlighted column has human-readable data:
![image](https://user-images.githubusercontent.com/46914665/200978070-87370860-ea6f-47e1-96e1-e35653659520.png)

3. The Fields view of the same attribute table, showing the Domain definition
![image](https://user-images.githubusercontent.com/46914665/200978135-fcd0c3f6-55c9-4ad6-b0e9-7af5b8c0855f.png)

Extraction script: 

```
library(rstudioapi)    
library(arcgisbinding) 
arc.check_product()    

#> product: ArcGIS Pro (13.0.2.36056)
#> license: Advanced
#> version: 1.0.1.300

arc.portal_connect('https://companyname.maps.arcgis.com/', 
                   'user.name',
                   askForPassword("AGOL password:"))

# > *** Current
# >   url		: https://companyname.maps.arcgis.com/
# >   version	: 10.2
# >   user		: user.name
# >   organization	: Company Name
# > *** Not signed in
# > 'https://www.arcgis.com/' 

my_survey <- 'https://services8.arcgis.com/h5RF6IOaBlFJtC7w/arcgis/rest/services/service_<obfuscated>/FeatureServer'

con <- arc.open(my_survey)

points <- arc.open(paste0(my_survey, '/', con@children$FeatureClass))

points_dat <- arc.select(points)
```

4. data structure in R, unaliased:
![image](https://user-images.githubusercontent.com/46914665/200978307-94e83d92-2ec7-4e36-800f-f19da75b165e.png)

and context - the code list from the 'choices' tab in the survey definition spreadsheet"
![image](https://user-images.githubusercontent.com/46914665/200978758-bde1c051-8efe-4def-97d0-f00ef0717671.png)

Obviously, I can use that to hack things back together myself, but I really don't want to.

**Comment by dpavlushko** [comment]
Thanks for the details. 
Unfortunately, `arc.select()` does not support table domains. The missing feature is a good candidate for implementation in the next release or so.
