### ISSUE TITLE
Will you be building in support for the simple features package?

### ISSUE THREAD

**Issue by nilescbn** [R-ArcGIS/r-bridge#8]
My agency just got the r-bridge installed and running this week. It will make workflows and the task of documenting them much much better, So thank you for building it. 

I'm wondering if you're contemplating building in support for the relatively new simple features package in R. That is, will you be creating arc.sf2sata and arc.data2sf() functions and building in support for sf objects in arc.write()?

Thanks again for your work on this.

**Comment by dpavlushko** [comment]
Yes, we are going to support sf package.

**Comment by dpavlushko** [comment]
sf supported in [1.0.1.229](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta)

**Comment by nilescbn** [comment]
Wonderful. Thank you!
