### ISSUE TITLE
Error: package or namespace load failed for ‘arcgisbinding’:  package ‘arcgisbinding’ was installed before R 4.0.0: please re-install it

### ISSUE THREAD

**Issue by victoriadancoMNRF** [R-ArcGIS/r-bridge#80]
**To Reproduce**

I am using R-4.3.0 and have the arcgisbinding version 1.0.1.305 and the error:

Error: package or namespace load failed for ‘arcgisbinding’:
 package ‘arcgisbinding’ was installed before R 4.0.0: please re-install it

when I call
> library(arcgisbinding)

**Comment by scdub** [comment]
@victoriadancoMNRF Thanks for the report, we can reproduce it and will pull the package until it can be correctly installed.

**Comment by JosiahParry** [comment]
@victoriadancoMNRF can you confirm that you are no longer encountering this? Thanks!

**Comment by scdub** [comment]
Based on our testing, R 4.3 works as expected now &mdash; if you're still having issues, feel free to create a new issue!
