### ISSUE TITLE
arc.env() does not grab workspace from GP tool environment settings

### ISSUE THREAD

**Issue by f-tonini** [R-ArcGIS/r-bridge#9]
I noticed that arc.env()$workspace only grabs workspace from environment settings set up at the ArcGIS Desktop GP menu level, not the GP tool level. Posted on GeoNet as well. 

```
env = arc.env()
wkspath <- env$workspace
#this path does not grab the GP tool environment settings, rather only the GP main menu env settings
print(wkspath)  
```

**Comment by scw** [comment]
[GeoNet post](https://geonet.esri.com/thread/191867-does-arcenv-get-workspace-only-from-gp-menu-settings) for details. Thanks for the report @f-tonini
