### ISSUE TITLE
please add support for r4.4.0

### ISSUE THREAD

**Issue by SpatLyu** [R-ArcGIS/r-bridge#90]
I have installed R4.4.0 in my win11 PC, but when i install `arcgisbinding`, I encountered the following error:
``` r
install.packages("arcgisbinding", 
                 repos ="https://r.esri.com", 
                 type = "win.binary")
#> Installing package into 'D:/application/R/pkgR'
#> (as 'lib' is unspecified)
#> Warning: unable to access index for repository https://r.esri.com/bin/windows/contrib/4.4:
#>   cannot open URL 'https://r.esri.com/bin/windows/contrib/4.4/PACKAGES'
#> Warning: package 'arcgisbinding' is not available as a binary package for this version of R
#> 
#> A version of this package for your version of R might be available elsewhere,
#> see the ideas at
#> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

<sup>Created on 2024-05-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Please add support for r4.4.0!

**Comment by orhuna** [comment]
@SpatLyu thanks for the issue, adding @JosiahParry and @mmachir

**Comment by JosiahParry** [comment]
@SpatLyu, this should be resolved now. Thank you for bringing it to our attention. @scw has helped make a PR to fix this which was merged earlier today. https://github.com/R-ArcGIS/r-arcgis.github.io/pull/11#event-12689170055

Can you please try installing again and let me know how it goes.

And, ps, @orhuna i _finally_ took you off the GitHub template. I hope this saves your inbox :P  Thank you for always pinging us!!!

**Comment by SpatLyu** [comment]
Good job,it goes well now:
``` r
install.packages("arcgisbinding", 
                 repos ="https://r.esri.com", 
                 type = "win.binary")
#> Installing package into 'D:/application/R/pkgR'
#> (as 'lib' is unspecified)
#> package 'arcgisbinding' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\86187\AppData\Local\Temp\RtmpuSSCpt\downloaded_packages
```

<sup>Created on 2024-05-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Thanks!

**Comment by scw** [comment]
Great, thanks for reporting back. Closing this for now, but feel free to open a new issue if you hit anything else.
