### ISSUE TITLE
arcgisbinding install error in ArcGIS Pro

### ISSUE THREAD

**Issue by dgoeldner** [R-ArcGIS/r-bridge#94]
When trying to run an R script in an ArcPro notebook, the error 
install.packages("arcgisbinding", NameError: name 'install' is not defined is returned.

**To Reproduce** In ArcPro, open a notebook and add the code
# Example of Using the R-arcgis bridge
install.packages("arcgisbinding", 
                 repos ="https://r.esri.com", 
                 type = "win.binary")
library(rstudioapi)    
library(arcgisbinding) 
arc.check_product()    

Returns the error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
In  [1]:
Line 2:     install.packages("arcgisbinding", 

NameError: name 'install' is not defined
---------------------------------------------------------------------------

The code works in R-Studio. Will it not work in a Jupyter Notebook?  All steps in r.esri.com were followed to load the packages and clone the environment.

**Comment by JosiahParry** [comment]
The error is from python. You can use it in a juptyer notebook if you are using an R kernel. It will not work with python.

**Comment by JosiahParry** [comment]
To install from ArcGIS Pro you can follow the installation steps at 
https://developers.arcgis.com/r-bridge/installation/#install-within-arcgis-pro-recommended
